export const CONFIG = {
  CANVAS_FPS: 30,
  UI_UPDATE_MS: 250,
  AUTO_SAVE_MS: 30000,
  MAX_VISUAL_PLANTS: 100,
  MAX_PARTICLES: 60,
  GROUND_RATIO: 0.55,

  PLANT_TYPES: {
    herb: {
      name: 'Herb',
      baseCost: 10,
      costScale: 1.12,
      generation: 1,
      growTime: 20,
      maxH: 18,
      color: '#6abf69',
      unlockAt: 0,
      description: 'A hardy herb. Generates 1 sunlight/s.',
    },
    sunflower: {
      name: 'Sunflower',
      baseCost: 100,
      costScale: 1.15,
      generation: 5,
      growTime: 40,
      maxH: 42,
      color: '#ffd700',
      unlockAt: 500,
      description: 'Bright and cheerful. 5 sunlight/s.',
    },
    lavender: {
      name: 'Lavender',
      baseCost: 2000,
      costScale: 1.18,
      generation: 20,
      growTime: 60,
      maxH: 30,
      color: '#b39ddb',
      unlockAt: 10000,
      description: 'Fragrant purple blooms. 20 sunlight/s.',
    },
    maple: {
      name: 'Maple Tree',
      baseCost: 50000,
      costScale: 1.22,
      generation: 100,
      growTime: 120,
      maxH: 58,
      color: '#ff7043',
      unlockAt: 200000,
      description: 'A majestic tree. 100 sunlight/s.',
    },
    cherry: {
      name: 'Cherry Blossom',
      baseCost: 1000000,
      costScale: 1.28,
      generation: 500,
      growTime: 240,
      maxH: 65,
      color: '#f48fb1',
      unlockAt: 5000000,
      description: 'Eternal beauty. 500 sunlight/s.',
    },
  },

  UPGRADES: {
    growthSpeed: {
      name: 'Fertile Soil',
      description: '+50% sunlight generation per level',
      baseCost: 50,
      costScale: 2.5,
      maxLevel: 50,
      icon: '🌱',
    },
    gardenBeauty: {
      name: 'Golden Light',
      description: 'Plants glow 20% brighter (visual)',
      baseCost: 30,
      costScale: 2.0,
      maxLevel: 20,
      icon: '☀️',
    },
    autoPlant: {
      name: "Nature's Way",
      description: 'Auto-plant an herb every 30s (−2s/lvl, min 6s)',
      baseCost: 200,
      costScale: 3.0,
      maxLevel: 12,
      icon: '🔄',
    },
    offlineGrowth: {
      name: 'Dream Garden',
      description: '+10% offline sunlight per level',
      baseCost: 500,
      costScale: 4.0,
      maxLevel: 10,
      icon: '🌙',
    },
  },

  SEASONS: [
    { name: 'Spring', threshold: 0, sky: ['#87ceeb', '#d4edfc'], ground: ['#7cb342', '#558b2f'], text: '#33691e' },
    { name: 'Summer', threshold: 10000, sky: ['#4fc3f7', '#b3e5fc'], ground: ['#43a047', '#2e7d32'], text: '#1b5e20' },
    { name: 'Autumn', threshold: 100000, sky: ['#ffcc80', '#ffe0b2'], ground: ['#a1887f', '#6d4c41'], text: '#3e2723' },
    { name: 'Winter', threshold: 1000000, sky: ['#b0bec5', '#eceff1'], ground: ['#e0e0e0', '#bdbdbd'], text: '#37474f' },
    { name: 'Eternal', threshold: 100000000, sky: ['#fff9c4', '#ffe082'], ground: ['#66bb6a', '#388e3c'], text: '#33691e' },
  ],

  MILESTONES: [
    { at: 100, msg: 'Your first sprouts emerge from the soil.' },
    { at: 1000, msg: 'The garden begins to flourish.' },
    { at: 5000, msg: 'Sunflowers turn to face the light.' },
    { at: 10000, msg: 'A warm summer breeze flows through.' },
    { at: 50000, msg: 'Lavender fills the air with calm.' },
    { at: 100000, msg: 'Autumn leaves dance in the wind.' },
    { at: 500000, msg: 'Maples stand tall and wise.' },
    { at: 1000000, msg: 'Winter brings quiet reflection.' },
    { at: 10000000, msg: 'Cherry blossoms paint the sky pink.' },
    { at: 100000000, msg: 'Your garden transcends the seasons.' },
  ],

  YOUTUBE_VIDEO_ID: 'dsvizrzLGI4',
};
