export const CONFIG = {
  CANVAS_FPS: 30,
  UI_UPDATE_MS: 250,
  AUTO_SAVE_MS: 30000,
  MAX_VISUAL_AGENTS: 200,
  MAX_PARTICLES: 80,

  AGENT_TYPES: {
    wanderer: {
      name: 'Wanderer',
      radius: 3,
      speed: 0.3,
      baseCost: 10,
      costScale: 1.15,
      generation: 1,
      color: '#ffb347',
      glowColor: 'rgba(255,179,71,0.18)',
      description: 'A gentle drifter. Generates 1 stardust/s.',
      unlockAt: 0,
    },
    gatherer: {
      name: 'Gatherer',
      radius: 4,
      speed: 0.5,
      baseCost: 100,
      costScale: 1.18,
      generation: 5,
      color: '#77dd77',
      glowColor: 'rgba(119,221,119,0.18)',
      description: 'A keen collector. Generates 5 stardust/s.',
      unlockAt: 500,
    },
    seeker: {
      name: 'Seeker',
      radius: 4,
      speed: 0.7,
      baseCost: 2000,
      costScale: 1.2,
      generation: 20,
      color: '#79d4f1',
      glowColor: 'rgba(121,212,241,0.18)',
      description: 'Forms networks with others. 20 stardust/s.',
      unlockAt: 10000,
    },
    sage: {
      name: 'Sage',
      radius: 5,
      speed: 0.2,
      baseCost: 50000,
      costScale: 1.25,
      generation: 100,
      color: '#b19cd9',
      glowColor: 'rgba(177,156,217,0.18)',
      description: 'An enlightened being. 100 stardust/s.',
      unlockAt: 200000,
    },
    architect: {
      name: 'Architect',
      radius: 6,
      speed: 0.15,
      baseCost: 1000000,
      costScale: 1.3,
      generation: 500,
      color: '#fdfd96',
      glowColor: 'rgba(253,253,150,0.18)',
      description: 'Shapes reality itself. 500 stardust/s.',
      unlockAt: 5000000,
    },
  },

  UPGRADES: {
    genRate: {
      name: 'Generation Boost',
      description: '+50% stardust generation per level',
      baseCost: 50,
      costScale: 2.5,
      maxLevel: 50,
      icon: '✨',
    },
    agentSpeed: {
      name: 'Swift Movement',
      description: 'Agents move 20% faster (visual)',
      baseCost: 30,
      costScale: 2.0,
      maxLevel: 20,
      icon: '💨',
    },
    autoSpawn: {
      name: 'Auto Spawn',
      description: 'Spawn a wanderer every 30s (−2s/lvl, min 6s)',
      baseCost: 200,
      costScale: 3.0,
      maxLevel: 12,
      icon: '🔄',
    },
    offlineBonus: {
      name: 'Offline Mastery',
      description: '+10% offline earnings per level',
      baseCost: 500,
      costScale: 4.0,
      maxLevel: 10,
      icon: '🌙',
    },
  },

  ERAS: [
    { name: 'Dawn', threshold: 0, bg: ['#ffecd2', '#fcb69f'], text: '#5a3e2b' },
    { name: 'Garden', threshold: 10000, bg: ['#c1dfc4', '#deecdd'], text: '#2d5a3d' },
    { name: 'Ocean', threshold: 100000, bg: ['#a1c4fd', '#c2e9fb'], text: '#1b3a5c' },
    { name: 'Cosmos', threshold: 1000000, bg: ['#0f0c29', '#302b63'], text: '#d0d0ff' },
    { name: 'Ethereal', threshold: 100000000, bg: ['#fceabb', '#f8b500'], text: '#4a3800' },
  ],

  MILESTONES: [
    { at: 100, msg: 'Your colony stirs to life.' },
    { at: 1000, msg: 'The agents begin to thrive.' },
    { at: 5000, msg: 'Gatherers emerge from the stardust.' },
    { at: 10000, msg: 'A new era dawns upon your world.' },
    { at: 50000, msg: 'Seekers reach out across the void.' },
    { at: 100000, msg: 'The ocean of possibility opens.' },
    { at: 500000, msg: 'Sages contemplate the infinite.' },
    { at: 1000000, msg: 'The cosmos beckons your colony.' },
    { at: 10000000, msg: 'Your agents transcend understanding.' },
    { at: 100000000, msg: 'Ethereal light embraces all.' },
  ],
};
